from enum import Enum

# Enums
class GenderEnum(str, Enum):
    female = "female"
    male = "male"
    other = "other"


class CountryEnum(str, Enum):
    Japan = "Japan"
    USA = "USA"
    Canada = "Canada"
    France = "France"
    Germany = "Germany"
    Italy = "Italy"
    Spain = "Spain"
    Australia = "Australia"
    Brazil = "Brazil"
    China = "China"
    India = "India"
    Mexico = "Mexico"
    Netherlands = "Netherlands"
    Singapore = "Singapore"
    SouthKorea = "South Korea"
    Sweden = "Sweden"
    UnitedArabEmirates = "United Arab Emirates"
    Ukraine = "Ukraine"
    UnitedKingdom = "United Kingdom"
    Russia = "Russia"
    Argentina = "Argentina"
    Austria = "Austria"
    Belgium = "Belgium"
    Chile = "Chile"
    Colombia = "Colombia"
    CzechRepublic = "Czech Republic"
    Denmark = "Denmark"
    Egypt = "Egypt"
    Finland = "Finland"
    Greece = "Greece"
    HongKong = "Hong Kong"
    Hungary = "Hungary"
    Indonesia = "Indonesia"
